export default [
  {
    name: 'Bitcoin',
    code: 'BTC',
    address: '1Gcn3Hfxbn3PvmsKXjHN1E9mgY8ziEXDHL',
    bgColor: 'bg-warning',
    imgBgColor: 'bg-dark',
    textColor: 'text-dark',
  },
  {
    name: 'Ethereum',
    code: 'ETH',
    address: '0xb54f47eef54fca71c37c456547582c16ccb8bad4',
    bgColor: 'bg-primary',
    imgBgColor: 'bg-dark',
    textColor: 'text-white',
  },
  {
    name: 'Binance USD',
    code: 'BUSD',
    address: '0xb54f47eef54fca71c37c456547582c16ccb8bad4',
    bgColor: 'bg-danger',
    imgBgColor: 'bg-dark',
    textColor: 'text-white',
  },
  {
    name: 'Tether',
    code: 'USDT',
    address: '0xb54f47eef54fca71c37c456547582c16ccb8bad4',
    bgColor: 'bg-success',
    imgBgColor: 'bg-dark',
    textColor: 'text-white',
  },
  {
    name: 'Cardano',
    code: 'ADA',
    address: 'DdzFFzCqrht6S6i7qSR6kpExvLa8GVy5q8ZJseohYBKrsureUiGAnTxZm9vtWyCU5Ss7YQYRx9hm1BmBsqnRZTtVQTEQtsxu8hzofmDw',
    bgColor: 'bg-ada',
    imgBgColor: 'bg-dark',
    textColor: 'text-white',
  },
  {
    name: 'Doge',
    code: 'DOGE',
    address: 'DJng9CQLaUsCoxArMqABfF2dvxQyXoKiQ6',
    bgColor: 'bg-dogecoin',
    imgBgColor: 'bg-dark',
    textColor: 'text-white',
  },
];